# Generated by Django 3.0.8 on 2021-02-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_tracker', '0002_comment_project_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
